create table if not exists clientes (id text primary key, empresa text, nit text, contacto text, telefono text, email text, direccion text, ciudad text, lat float, lng float, activo boolean default true, created_at timestamptz default now(), updated_at timestamptz);
create table if not exists extintores (id text primary key, "clienteId" text, serial text, ubicacion text, tipo text, capacidad text, libras float, mmt int, "fechaVencimiento" text, estado text default 'activo', created_at timestamptz default now(), updated_at timestamptz);
create table if not exists recolecciones (id text primary key, "clienteId" text, "mensajeroId" text, extintores jsonb, estado text, prioridad text, "fechaProgramada" text, observaciones text, created_at timestamptz default now(), updated_at timestamptz);
create table if not exists entregas (id text primary key, "clienteId" text, "mensajeroId" text, extintores jsonb, estado text, "fechaProgramada" text, "firmaCliente" text, "correoEnvio" text, created_at timestamptz default now(), updated_at timestamptz);
create table if not exists laboratorio (id text primary key, extintor text, "clienteId" text, "tecnicoId" text, estado text, prioridad text, diagnostico text, "materialesRequeridos" jsonb, "aprobadoCliente" boolean default false, created_at timestamptz default now(), updated_at timestamptz);
create table if not exists visitas (id text primary key, "clienteId" text, "vendedorId" text, "fechaProgramada" text, estado text, tipo text, "extintoresInspeccionados" jsonb, "observacionesGenerales" text, created_at timestamptz default now(), updated_at timestamptz);
create table if not exists prestamos (id text primary key, extintor text, "clienteId" text, "autorizadoPor" text, "fechaPrestamo" text, "fechaDevolucionEstimada" text, estado text, observaciones text, created_at timestamptz default now(), updated_at timestamptz);
create table if not exists alertas (id text primary key, tipo text, mensaje text, "usuarioDestino" text, leida boolean default false, created_at timestamptz default now(), updated_at timestamptz);
create table if not exists materiales (id text primary key, nombre text, categoria text, precio int, stock int, activo boolean default true, created_at timestamptz default now(), updated_at timestamptz);
create table if not exists auditoria (id text primary key, "usuarioId" text, accion text, modulo text, created_at timestamptz default now());
create table if not exists usuarios (id text primary key, nombre text, email text, password text, rol text, activo boolean default true, created_at timestamptz default now(), updated_at timestamptz);
create table if not exists ubicaciones (id text primary key, "usuarioId" text, lat float, lng float, ts timestamptz, nombre text);
alter table clientes enable row level security;
alter table extintores enable row level security;
alter table recolecciones enable row level security;
alter table entregas enable row level security;
alter table laboratorio enable row level security;
alter table visitas enable row level security;
alter table prestamos enable row level security;
alter table alertas enable row level security;
alter table materiales enable row level security;
alter table auditoria enable row level security;
alter table usuarios enable row level security;
alter table ubicaciones enable row level security;
create policy "acceso_publico" on clientes for all using (true) with check (true);
create policy "acceso_publico" on extintores for all using (true) with check (true);
create policy "acceso_publico" on recolecciones for all using (true) with check (true);
create policy "acceso_publico" on entregas for all using (true) with check (true);
create policy "acceso_publico" on laboratorio for all using (true) with check (true);
create policy "acceso_publico" on visitas for all using (true) with check (true);
create policy "acceso_publico" on prestamos for all using (true) with check (true);
create policy "acceso_publico" on alertas for all using (true) with check (true);
create policy "acceso_publico" on materiales for all using (true) with check (true);
create policy "acceso_publico" on auditoria for all using (true) with check (true);
create policy "acceso_publico" on usuarios for all using (true) with check (true);
create policy "acceso_publico" on ubicaciones for all using (true) with check (true);
